### ISSUE TITLE
Is it possible to include some external JS lib ? 

### ISSUE THREAD

**Issue by prabel** [abner/flutter_js#12]
Hi,
I would like to run some simple JS script, for example this one:
```
function js_function(message) {
  var web3 = new Web3();
  var account = web3.eth.accounts.create();
  var signedMessage = web3.eth.accounts.sign(message, account.privateKey);
  return signedMessage;
}
js_function('test_message');
```
But for right now it returns only 
```
Uncaught ReferenceError: Web3 is not defined
```

So is it possible to attach Web3 or some other API and execute it using this package?

**Comment by hebaothman** [comment]
Any new updates for this request

**Comment by abner** [comment]
You should load the lib script by yourself. Read it from a external source (asset file, network request, whatever) and load it with eval.
I usually generate a bundle using some javascript bundler (webpack, parcel, rollup ... anything of your precerence) and which expose some api methods and objects over a global object. I already tested using moment, ajv, and redux (per example).
Just you need to know that neither the lib or your code should rely on functions like setTimeout, setInterval, neither promises, which are not provided by the underly javascript engines.

I will close because it is more a support request than a library issue. But you're welcome to ask any further questions.

**Comment by stonesong** [comment]
Hi @abner do you have some example ? I can't manage to run a js library that I bundled with webpack.
First I created a test.js file like so:
`class Render {
  constructor() {
    this.message = 'Render instance created';
  }

  getMessage() {
    return 'This is a message from the Render class.';
  }

  static staticMethod() {
    return 'This is a static method call from Render.';
  }
}

module.exports = Render;
  `
  
  and then I loaded the file with flutter_js and executed it like so:
  `
   String message = jsRuntime.evaluate("""
          var renderInstance = new Render();
          renderInstance.getMessage();
        """).stringResult;
      print('Message: $message'); 
      `
      
      So far no problems, it is working.
      
      Then I moved this test.js file info an src/index.js of a library and bundled it like so:
`  const path = require('path');

module.exports = {
  mode: 'production',
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'test.js',
    library: 'testJs',
    libraryTarget: 'umd',
  },
};`

Moved the bundled file instead of my test.js in Flutter that was working before, but then no way to have it working whatever I do:
`      String message = jsRuntime.evaluate("""
          var renderInstance = new testJs.Render();
          renderInstance.getMessage();
        """).stringResult;
      print('Message: $message'); // Expected output from getMessage()

      String message2 = jsRuntime.evaluate("""
          var renderInstance = new Render();
          renderInstance.getMessage();
        """).stringResult;
      print('Message: $message2'); // Expected output from getMessage()`
      
      I always get the:
      flutter: Message: ERROR: Can't find variable: testJs 
  at global code@
flutter: Message: ERROR: Can't find variable: Render 
  at global code@
  
  What am I doing wrong ? Thanks a lot in advance
