### ISSUE TITLE
Usage with complex libraries

### ISSUE THREAD

**Issue by emvaized** [abner/flutter_js#29]
Is it possible to use flutter_js with complex libraries like [mercury-parses](https://github.com/postlight/mercury-parser)?

I tried to store locally `src`, `dist` and `scripts` folders, declare them in a pubspec file, and use lin code ike the following:
```
flutterJs = getJavascriptRuntime();
    try {
      String ajvJS = await rootBundle.loadString("assets/dist/mercury.js");
      flutterJs.evaluate(ajvJS + "");
      final evalAjv = flutterJs.evaluate('''
      Mercury.parse('https://google.com').then(result => console.log(result))
      ''');
      print(evalAjv.stringResult);
    }
```
but keep getting the following error:
`ERROR: undefined is not an object (evaluating 'Mercury.parse')`

Maybe in order to use complex libraries it is needed to manually import each js file with the `rootBundle.loadString` command?

Thanks in advance

**Comment by ankit-yv** [comment]
@abner your library is super easy to use kudos for that 👍👍. can you pls suggest some workaround so that we can use 3rd party javascript libraries inside js codebase?

**Comment by abner** [comment]
First of all thaks!

I usually use js bundlers (webpack, parcel, rollup) to generate a bundle of the javascript i will use inside the Flutter app. 

You also need to know the engine (QuickJS) or JavascriptCore limitations. I try to limit the focus to be very minimal, because there is no intent here to produce a Flutter App with lot o features in JS  you could easily do in  Dart. I'm focused here in share web backend/frontend logic (which generally i lookup to write abstracting away the platform internal aspects) within my Flutter app through this engine. So, flutter_js works better if your dependencies follow the same principles.
