### ISSUE TITLE
Yes, you just need to setup the native configuration (AndroidManifest.xml in Android and entitlement files on IOS) to allow your app to communicate with external sources

### ISSUE THREAD

**Issue by TejaDroid** [abner/flutter_js#73]
Yes, you just need to setup the native configuration (AndroidManifest.xml in Android and entitlement files on IOS) to allow your app to communicate with external sources

_Originally posted by @abner in https://github.com/abner/flutter_js/issues/30#issuecomment-812950512_

Will you please give me some references on how to use in native configuration?
I have a Javascript file that is hosted somewhere and I want to call the functions of that in the flutter App. Now we had tried in two ways. The first is _webViewController.runJavascriptReturningResult() of browser which works fine, but we have some limitation that we had to load Webview for just one single method of js.
The second is with the current plugins method of JsRuntime.evaluate() which does not work with js core functions like window.alert();

**Comment by abner** [comment]
JsRuntime is just Javascript Runtime. It is not a browser implementation, so there is no window, no websocket, no xhr, and no fetch inside it. Flutter_js added some convenient polyfills to xhr and fetch, but there is no intention to bring another browser apis, because a lot of that does not make sense inside a Flutter application. Example: If from your javascript you want to show some messages to the user, you can provide yourself a Dart callback using onMessage into the jsRuntime and in the callback implementation, you can trigger a call to show a Flutter Dialog Box to the user. The idea of flutter_js is to allow evaluate dynamic javascript code inside a Flutter App, but not implement interactions to the user neither make the Flutter App being developed as running in a WebBrowser. For this, we can leverage on WebViews, an so have a browser running inside the Flutter Application.
